### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by slack8182** [ArthurMoore85/romulus#11]
When I try to install using pip install -r requirements.txt or sudo pip install -r requirements.txt I get this error message:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-JtLykk/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9BRsUK-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-JtLykk/cffi
Storing debug log for failure in /root/.pip/pip.log

Any idea what's wrong? I'm using the RetroPie image on a raspberry pi 3 and I made sure I installed all the required packages

**Comment by ArthurMoore85** [comment]
Thanks for reporting this.
I'll investigate as soon as I can.

**Comment by ArthurMoore85** [comment]
What distro are you using?
I suspect you are trying to install this directly on to your Retropie? If so, this is in fact to run on a Linux desktop.
